# Generated by Django 2.2.24 on 2024-07-20 10:04
from django.db import migrations
# import phonenumbers


# def copy_phone_numbers(apps, schema_editor):
#     Flat = apps.get_model('property', 'Flat')
#     for flat in Flat.objects.all():
#         if flat.owners_phonenumber:
#             normalized_phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
#             if phonenumbers.is_valid_number_for_region(normalized_phone, 'RU'):
#                 flat.owner_pure_phone = normalized_phone
#             else:
#                 flat.owner_pure_phone = ''
#             flat.save()
#

class Migration(migrations.Migration):
    dependencies = [
        ('property', '0006_auto_20240719_2108'),
    ]

    operations = [
        # migrations.RunPython(copy_phone_numbers)
    ]
