# Generated by Django 2.2.24 on 2024-07-20 10:04
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0006_auto_20240719_2108'),
    ]

    operations = [
    ]
