# Generated by Django 2.2.24 on 2024-07-20 11:31

from django.db import migrations
import phonenumbers

def copy_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all.iterator():
        if not flat.owners_phonenumber:
            continue

        normalized_phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        flat.owner_pure_phone = normalized_phone if phonenumbers.is_valid_number_for_region(normalized_phone, 'RU') else ''
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(copy_phone_numbers)
    ]
