# Generated by Django 3.2.12 on 2024-08-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_alter_flat_has_balcony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner',
            field=models.CharField(db_column='owner', db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
    ]
